# Generated by Codex on 2026-07-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forward_statuses(apps, schema_editor):
    ToBuyItem = apps.get_model("procurement", "ToBuyItem")
    ToBuyItem.objects.filter(status="pending").update(status="requested")
    ToBuyItem.objects.filter(status="bought").update(status="received")


def reverse_statuses(apps, schema_editor):
    ToBuyItem = apps.get_model("procurement", "ToBuyItem")
    ToBuyItem.objects.filter(status="received").update(status="bought")
    ToBuyItem.objects.exclude(status="bought").update(status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0002_tobuyitem_scope_created_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tobuyitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("approved", "Approved"),
                    ("ordered", "Ordered"),
                    ("received", "Received"),
                    ("cancelled", "Cancelled"),
                ],
                default="requested",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="tobuyitem",
            name="vendor_name",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tobuyitem",
            name="actual_unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tobuyitem",
            name="purchaser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tobuyitem",
            name="ordered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tobuyitem",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ToBuyReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_key", models.CharField(max_length=512, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "to_buy_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="procurement.tobuyitem",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(forward_statuses, reverse_statuses),
    ]
