# Generated by Django 5.1.15 on 2026-07-08 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryproduct_image_key'),
        ('printing', '0019_filament_adjustment'),
        ('procurement', '0003_tobuy_lifecycle_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tobuyitem',
            name='moved_to_inventory_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tobuyitem',
            name='resulting_printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='printing.printprinter'),
        ),
        migrations.AddField(
            model_name='tobuyitem',
            name='resulting_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventoryproduct'),
        ),
        migrations.AddField(
            model_name='tobuyitem',
            name='resulting_spool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='printing.filamentspool'),
        ),
    ]
