# Generated by Django 5.1.15 on 2026-07-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0019_filament_adjustment"),
        ("procurement", "0004_tobuyitem_moved_to_inventory_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tobuyitem",
            name="source_spool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="low_stock_to_buy_items",
                to="printing.filamentspool",
            ),
        ),
    ]