# Generated by Django 5.1.15 on 2026-07-18 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_member_registration_and_email_verification'),
        ('makerspaces', '0042_makerspace_presence_preset_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('superseded', 'Superseded'), ('membership_revoked', 'Membership revoked'), ('user_ended', 'User ended')], max_length=24)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_presence_sessions', to='accounts.user')),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makerspaces.makerspace')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='makerspaces.makerspacemembership')),
            ],
            options={
                'indexes': [models.Index(fields=['makerspace', 'expires_at'], name='presence_pr_makersp_b6fde3_idx'), models.Index(fields=['member', 'makerspace', 'expires_at'], name='presence_pr_member__75e77d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('started_at'))), name='presence_session_expires_after_start')],
            },
        ),
    ]
