# Generated by Django 5.1.15 on 2026-06-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiclients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclient',
            name='client_type',
            field=models.CharField(choices=[('browser', 'Browser'), ('server', 'Server')], default='server', max_length=20),
        ),
        migrations.AddField(
            model_name='apiclient',
            name='rate_limit_tier',
            field=models.CharField(choices=[('public', 'Public'), ('standard', 'Standard'), ('trusted', 'Trusted')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='apiclient',
            name='scopes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
