# Generated by Django 5.1.15 on 2026-07-16 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('makerspaces', '0033_enable_bookings_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookableSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('dev_room', 'Development room'), ('bench', 'Bench'), ('meeting', 'Meeting room'), ('other', 'Other')], default='other', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('image_key', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookable_spaces', to='makerspaces.makerspace')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No-show')], default='booked', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.bookablespace')),
            ],
            options={
                'ordering': ['starts_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='bookablespace',
            index=models.Index(fields=['makerspace', 'is_active', 'name'], name='bookspace_ms_active_idx'),
        ),
        migrations.AddIndex(
            model_name='bookablespace',
            index=models.Index(fields=['makerspace', 'is_public', 'is_active'], name='bookspace_public_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookablespace',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 0)), name='bookspace_capacity_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['space', 'status', 'starts_at'], name='booking_space_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['space', 'ends_at'], name='booking_space_end_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='booking_end_after_start'),
        ),
    ]
