# Generated by Django 5.1.15 on 2026-07-16 20:36

import apps.forms_schema.validation
from django.db import migrations, models


def booked_to_confirmed(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    Booking.objects.filter(status='booked').update(status='confirmed')


def confirmed_to_booked(apps, schema_editor):
    '''Rollback is lossy because the old application has no approval states.'''
    Booking = apps.get_model('bookings', 'Booking')
    Booking.objects.filter(status='confirmed').update(status='booked')
    Booking.objects.filter(status__in=('pending', 'rejected')).update(
        status='cancelled'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0036_booking_requester_notifications'),
        ('bookings', '0002_public_booking_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookablespace',
            name='approval_mode',
            field=models.CharField(choices=[('instant', 'Instant confirmation'), ('approve', 'Staff approval required')], default='instant', max_length=16),
        ),
        migrations.AddField(
            model_name='bookablespace',
            name='custom_form',
            field=models.JSONField(blank=True, default=None, null=True, validators=[apps.forms_schema.validation.validate_form_schema]),
        ),
        migrations.AddField(
            model_name='bookablespace',
            name='requester_notifications_enabled',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='custom_answers',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(booked_to_confirmed, confirmed_to_booked),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No-show')], default='confirmed', max_length=16),
        ),
    ]
