# Generated by Django 5.1.15 on 2026-07-17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_public_booking_custom_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookablespace',
            name='min_booking_duration_minutes',
            field=models.PositiveIntegerField(
                default=30,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name='bookablespace',
            name='max_booking_duration_minutes',
            field=models.PositiveIntegerField(
                default=480,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name='bookablespace',
            name='booking_lead_time_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='bookablespace',
            name='max_booking_advance_days',
            field=models.PositiveIntegerField(
                default=30,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddConstraint(
            model_name='bookablespace',
            constraint=models.CheckConstraint(
                condition=models.Q(('min_booking_duration_minutes__gte', 1)),
                name='bookspace_min_duration_positive',
            ),
        ),
        migrations.AddConstraint(
            model_name='bookablespace',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('max_booking_duration_minutes__gte', models.F(
                        'min_booking_duration_minutes'
                    ))
                ),
                name='bookspace_max_duration_gte_min',
            ),
        ),
        migrations.AddConstraint(
            model_name='bookablespace',
            constraint=models.CheckConstraint(
                condition=models.Q(('max_booking_advance_days__gte', 1)),
                name='bookspace_advance_positive',
            ),
        ),
    ]
