# Generated by Django 5.1.15 on 2026-07-08 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('makerspaces', '0026_makerspace_domain_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=16)),
                ('event', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('url_path', models.CharField(blank=True, max_length=300)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='makerspaces.makerspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['makerspace', 'read_at', '-created_at'], name='notificatio_makersp_16f432_idx'), models.Index(fields=['makerspace', '-created_at'], name='notificatio_makersp_4480f1_idx')],
            },
        ),
    ]
