# Generated by Django 5.1.15 on 2026-07-15 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = True

    dependencies = [
        ('inventory', '0009_inventoryproduct_image_key'),
        ('machines', '0004_machine_image_key'),
        ('makerspaces', '0027_enable_machines_module'),
        ('printing', '0019_filament_adjustment'),
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='machine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='machines.machine'),
        ),
        migrations.RemoveConstraint(
            model_name='warranty',
            name='warranty_exactly_one_host',
        ),
        migrations.AddConstraint(
            model_name='warranty',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset__isnull', False), ('machine__isnull', True), ('printer__isnull', True)), models.Q(('asset__isnull', True), ('machine__isnull', True), ('printer__isnull', False)), models.Q(('asset__isnull', True), ('machine__isnull', False), ('printer__isnull', True)), _connector='OR'), name='warranty_exactly_one_host'),
        ),
    ]
