# Generated by Django 5.1.15 on 2026-07-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0004_pii_write_fence'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='piiblindindex',
            new_name='encryption__makersp_239b44_idx',
            old_name='encryption__makersp_9d5c77_idx',
        ),
        migrations.AlterField(
            model_name='piiglobalwritefence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='piimakerspacewritefence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
