# Generated by Django 6.0 on 2026-07-19

from django.db import migrations


FORWARD_SQL = """
CREATE FUNCTION pii_fence_machine_service_request() RETURNS trigger AS $$
DECLARE tenant_id bigint;
BEGIN
  SELECT machine.makerspace_id INTO tenant_id
  FROM machines_servicebucket bucket
  JOIN machines_machine machine ON machine.id = bucket.machine_id
  WHERE bucket.id = NEW.bucket_id
  FOR KEY SHARE OF bucket, machine;
  PERFORM pii_assert_mapped_write_allowed(tenant_id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER pii_fence_machine_service_request_trigger
BEFORE INSERT OR UPDATE OF requester_name, contact_email, contact_phone
ON machines_machineservicerequest
FOR EACH ROW EXECUTE FUNCTION pii_fence_machine_service_request();
"""


REVERSE_SQL = """
DROP TRIGGER IF EXISTS pii_fence_machine_service_request_trigger ON machines_machineservicerequest;
DROP FUNCTION IF EXISTS pii_fence_machine_service_request();
"""


class Migration(migrations.Migration):

    dependencies = [
        ("encryption", "0005_rename_encryption__makersp_9d5c77_idx_encryption__makersp_239b44_idx_and_more"),
        ("machines", "0010_member_service_request_owner"),
    ]

    operations = [migrations.RunSQL(FORWARD_SQL, REVERSE_SQL)]
