# Generated by Django 5.1.15 on 2026-06-12 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_requests', '0009_public_tool_loan_qr_ids'),
        ('makerspaces', '0010_makerspace_default_loan_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarerequest',
            name='return_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='hardwarerequest',
            name='return_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HardwareEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('request_received', 'Request Received'), ('request_accepted', 'Request Accepted'), ('request_rejected', 'Request Rejected'), ('request_issued', 'Request Issued'), ('request_returned', 'Request Returned'), ('return_reminder', 'Return Reminder')], max_length=32)),
                ('subject', models.CharField(max_length=200)),
                ('text_body', models.TextField()),
                ('html_body', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_email_templates', to='makerspaces.makerspace')),
            ],
            options={
                'ordering': ['makerspace__name', 'key'],
                'constraints': [models.UniqueConstraint(fields=('makerspace', 'key'), name='uniq_hardware_email_template_key_per_space')],
            },
        ),
    ]
