# Generated by Django 5.1.15 on 2026-06-29 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0009_qrscanevent_qrscan_ms_qrcode_created_idx_and_more'),
        ('hardware_requests', '0020_return_reminder_due_index'),
        ('makerspaces', '0024_makerspace_public_print_status_lookup_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnevent',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boxes.box'),
        ),
        migrations.CreateModel(
            name='PublicProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problem_reports', to='hardware_requests.publictoolloan')),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_problem_reports', to='makerspaces.makerspace')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hardware_requests.hardwarerequest')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['makerspace', 'resolved_at'], name='hardware_re_makersp_4e3782_idx')],
            },
        ),
    ]
