# Generated by Django 5.1.15 on 2026-07-16 20:36

import apps.forms_schema.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_makerspace_start_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_form',
            field=models.JSONField(blank=True, default=None, null=True, validators=[apps.forms_schema.validation.validate_form_schema]),
        ),
        migrations.AddField(
            model_name='event',
            name='location_kind',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('other', 'Other')], default='other', max_length=8),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='custom_answers',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
