# Generated by Django 5.1.15 on 2026-07-18 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0005_rename_encryption__makersp_9d5c77_idx_encryption__makersp_239b44_idx_and_more'),
        ('events', '0005_event_registration_email_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('member__isnull', False), ('status__in', ('registered', 'waitlisted'))), fields=('event', 'member'), name='uniq_active_event_registration_member'),
        ),
    ]
