# Generated by Django 5.1.15 on 2026-06-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0006_qr_scan_event_immutable_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrscanevent',
            name='context',
            field=models.CharField(choices=[('issue', 'Issue'), ('return', 'Return'), ('inventory_check', 'Inventory Check'), ('reassignment', 'Reassignment'), ('scanner_lookup', 'Scanner Lookup')], max_length=32),
        ),
    ]
