# Generated by Django 6.0.7 on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformUpdateSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("automatic_updates_enabled", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("failed", "Failed"),
                        ],
                        default="idle",
                        max_length=16,
                    ),
                ),
                ("current_version", models.CharField(blank=True, max_length=80)),
                ("available_version", models.CharField(blank=True, max_length=80)),
                ("target_version", models.CharField(blank=True, max_length=80)),
                ("update_requested_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_backup_at", models.DateTimeField(blank=True, null=True)),
                ("last_backup_name", models.CharField(blank=True, max_length=120)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
