# Generated by Django 5.1.15 on 2026-07-16 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


IMMUTABILITY_SQL = """
CREATE OR REPLACE FUNCTION maintenance_reject_log_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' AND current_setting('app.allow_immutable_delete', true) = 'on' THEN
        RETURN OLD;
    END IF;
    RAISE EXCEPTION 'append-only/immutable table: % not allowed', TG_OP;
END;
$$;

CREATE TRIGGER maintenance_maintenancelog_no_update
BEFORE UPDATE ON maintenance_maintenancelog
FOR EACH ROW EXECUTE FUNCTION maintenance_reject_log_mutation();

CREATE TRIGGER maintenance_maintenancelog_no_delete
BEFORE DELETE ON maintenance_maintenancelog
FOR EACH ROW EXECUTE FUNCTION maintenance_reject_log_mutation();
"""

IMMUTABILITY_REVERSE_SQL = """
DROP TRIGGER IF EXISTS maintenance_maintenancelog_no_update
ON maintenance_maintenancelog;
DROP TRIGGER IF EXISTS maintenance_maintenancelog_no_delete
ON maintenance_maintenancelog;
DROP FUNCTION IF EXISTS maintenance_reject_log_mutation();
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('makerspaces', '0034_enable_maintenance_module'),
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.TextField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('parts_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='machines.machine')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLogDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(max_length=500, unique=True)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='maintenance.maintenancelog')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('interval_days', models.PositiveIntegerField()),
                ('next_due', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='machines.machine')),
            ],
            options={
                'ordering': ['next_due', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenancelog',
            index=models.Index(fields=['machine', 'performed_at'], name='maintenance_log_machine_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancelog',
            constraint=models.CheckConstraint(condition=models.Q(('cost__isnull', True), ('cost__gte', 0), _connector='OR'), name='maintenance_log_cost_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['machine', 'is_active', 'next_due'], name='maintenance_due_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceschedule',
            constraint=models.CheckConstraint(condition=models.Q(('interval_days__gt', 0)), name='maintenance_interval_days_positive'),
        ),
        migrations.RunSQL(IMMUTABILITY_SQL, IMMUTABILITY_REVERSE_SQL),
    ]
