# Generated by Django 5.1.15 on 2026-06-12 05:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0009_makerspace_branding_config_and_more'),
        ('printing', '0002_print_request_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='printrequest',
            name='estimated_filament_grams',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='printrequest',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='printrequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FilamentSpool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('lot_code', models.CharField(blank=True, max_length=100)),
                ('initial_weight_grams', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('remaining_weight_grams', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filament_spools', to='makerspaces.makerspace')),
            ],
            options={
                'ordering': ['makerspace__name', 'printer__name', 'material', 'color'],
            },
        ),
        migrations.AddField(
            model_name='printrequest',
            name='filament_spool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_requests', to='printing.filamentspool'),
        ),
        migrations.CreateModel(
            name='PrintPrinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], db_index=True, default='active', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_printers', to='makerspaces.makerspace')),
            ],
            options={
                'ordering': ['makerspace__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='filamentspool',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filament_spools', to='printing.printprinter'),
        ),
        migrations.AddField(
            model_name='printrequest',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_requests', to='printing.printprinter'),
        ),
        migrations.AddConstraint(
            model_name='printprinter',
            constraint=models.UniqueConstraint(fields=('makerspace', 'name'), name='uniq_print_printer_makerspace_name'),
        ),
    ]
