# Generated by Django 5.1.15 on 2026-06-15 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0004_printrequest_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printrequest',
            name='requested_filament_spool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_for_print_requests', to='printing.filamentspool'),
        ),
        migrations.AddField(
            model_name='printrequest',
            name='requester_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
