# Generated by Django 5.1.15 on 2026-06-25 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_accepted_by(apps, schema_editor):
    print_request = apps.get_model("printing", "PrintRequest")
    audit_log = apps.get_model("audit", "AuditLog")

    for action in ("print.accepted", "print.reprinted"):
        rows = (
            audit_log.objects.filter(action=action, actor_id__isnull=False)
            .exclude(target_id="")
            .order_by("created_at")
            .values_list("target_id", "actor_id")
        )
        for target_id, actor_id in rows:
            try:
                request_id = int(target_id)
            except (TypeError, ValueError):
                continue
            print_request.objects.filter(
                pk=request_id,
                accepted_by_id__isnull=True,
            ).update(accepted_by_id=actor_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_auditlog_purge_delete_guard"),
        ('printing', '0015_printrequest_contact_email_lower_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manualprintlog',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='manualprintlog',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='manualprintlog',
            name='requester_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='printrequest',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_print_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_accepted_by, noop_reverse),
    ]



