# Generated by Codex on 2026-07-08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0017_manualprintlog_outcome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="printrequest",
            name="run_printer_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="printrequest",
            name="run_printer_model",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="printrequest",
            name="run_spool_label",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="printrequest",
            name="run_spool_material",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="printrequest",
            name="run_spool_color",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="printrequest",
            name="run_estimated_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="printrequest",
            name="run_planned_filament_grams",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
