# Generated by Django 5.1.15 on 2026-07-08 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0024_makerspace_public_print_status_lookup_policy'),
        ('printing', '0018_printrequest_run_sheet_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilamentAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reserve', 'Reserve'), ('reconcile', 'Reconcile'), ('manual', 'Manual'), ('correction', 'Correction'), ('retire', 'Retire')], max_length=16)),
                ('grams', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('filament_spool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='printing.filamentspool')),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filament_adjustments', to='makerspaces.makerspace')),
                ('manual_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filament_adjustments', to='printing.manualprintlog')),
                ('print_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filament_adjustments', to='printing.printrequest')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['filament_spool', 'created_at'], name='printing_fi_filamen_e858b8_idx')],
            },
        ),
        migrations.RunSQL(
            sql="""
CREATE OR REPLACE FUNCTION printing_filament_adjustment_reject_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'append-only/immutable table: % not allowed', TG_OP;
END;
$$;

CREATE TRIGGER printing_filamentadjustment_no_update
BEFORE UPDATE ON printing_filamentadjustment
FOR EACH ROW EXECUTE FUNCTION printing_filament_adjustment_reject_mutation();

CREATE TRIGGER printing_filamentadjustment_no_delete
BEFORE DELETE ON printing_filamentadjustment
FOR EACH ROW EXECUTE FUNCTION printing_filament_adjustment_reject_mutation();
""",
            reverse_sql="""
DROP TRIGGER IF EXISTS printing_filamentadjustment_no_update ON printing_filamentadjustment;
DROP TRIGGER IF EXISTS printing_filamentadjustment_no_delete ON printing_filamentadjustment;
DROP FUNCTION IF EXISTS printing_filament_adjustment_reject_mutation();
""",
        ),
    ]
