# Generated by Django 5.1.15 on 2026-06-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0002_makerspacemembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makerspacemembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('guest_admin', 'Guest Admin'), ('print_manager', 'Print Manager')], default='admin', max_length=32),
        ),
    ]
