# Generated by Django 5.1.15 on 2026-06-12 04:02

import apps.makerspaces.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0008_rename_admin_role_add_inventory_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspace',
            name='branding_config',
            field=models.JSONField(blank=True, default=apps.makerspaces.models.default_branding_config),
        ),
        migrations.AddField(
            model_name='makerspace',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=apps.makerspaces.models.default_enabled_modules),
        ),
        migrations.AddField(
            model_name='makerspace',
            name='theme_config',
            field=models.JSONField(blank=True, default=apps.makerspaces.models.default_theme_config),
        ),
        migrations.CreateModel(
            name='TenantFrontend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=apps.makerspaces.models.generate_publishable_key, max_length=64, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('frontend_type', models.CharField(choices=[('public_portal', 'Public Portal'), ('staff_admin', 'Staff Admin'), ('guest_handover', 'Guest Handover'), ('scanner', 'Scanner'), ('kiosk', 'Kiosk'), ('superadmin_console', 'Superadmin Console'), ('third_party', 'Third Party')], default='public_portal', max_length=32)),
                ('allowed_origins', models.JSONField(blank=True, default=list)),
                ('enabled_modules', models.JSONField(blank=True, default=list)),
                ('theme_config', models.JSONField(blank=True, default=dict)),
                ('branding_config', models.JSONField(blank=True, default=dict)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenant_frontends', to=settings.AUTH_USER_MODEL)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frontends', to='makerspaces.makerspace')),
            ],
            options={
                'indexes': [models.Index(fields=['makerspace', 'frontend_type', 'is_active'], name='makerspaces_makersp_2a9721_idx')],
            },
        ),
    ]
