# Generated by Django 5.1.15 on 2026-06-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0009_makerspace_branding_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspace',
            name='default_loan_days',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
