# Generated by Django 5.1.15 on 2026-06-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0017_delete_tenantfrontend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makerspace',
            name='frontend_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
