# Generated by Django 5.1.15 on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makerspaces", "0024_makerspace_public_print_status_lookup_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="makerspace",
            name="filament_low_stock_threshold_grams",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]