# Generated by Django 5.1.15 on 2026-07-08

import apps.makerspaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makerspaces", "0025_makerspace_filament_low_stock_threshold_grams"),
    ]

    operations = [
        migrations.AddField(
            model_name="makerspace",
            name="domain_verification_token",
            field=models.CharField(
                default=apps.makerspaces.models.generate_domain_verification_token,
                editable=False,
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="makerspace",
            name="domain_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="makerspace",
            name="frontend_domain_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]