# Generated by Django 5.1.15 on 2026-07-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0027_enable_machines_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspace',
            name='frontend_domain_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
