# Generated by Django 5.1.15 on 2026-07-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0035_add_machine_manager_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspace',
            name='booking_requester_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
