# Generated by Django 5.1.15 on 2026-07-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0036_booking_requester_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspace',
            name='mattermost_webhook_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='makerspace',
            name='slack_webhook_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
