# Generated by Django 5.1.15 on 2026-07-17

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makerspaces", "0037_makerspace_mattermost_webhook_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakerspaceRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=80)),
                ("granted_actions", models.JSONField(blank=True, default=list)),
                ("legacy_role", models.CharField(blank=True, choices=[("space_manager", "Space Manager"), ("guest_admin", "Guest Admin"), ("inventory_manager", "Inventory Manager"), ("print_manager", "Print Manager"), ("machine_manager", "Machine Manager")], max_length=32, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_protected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("makerspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="roles", to="makerspaces.makerspace")),
            ],
            options={
                "ordering": ["name", "id"],
                "indexes": [django.contrib.postgres.indexes.GinIndex(fields=["granted_actions"], name="makerspacerole_actions_gin")],
                "constraints": [
                    models.UniqueConstraint(models.functions.Lower("name"), "makerspace", name="makerspacerole_ci_name_uniq"),
                    models.UniqueConstraint(models.functions.Lower("slug"), "makerspace", name="makerspacerole_ci_slug_uniq"),
                    models.UniqueConstraint(condition=models.Q(("legacy_role__isnull", False)), fields=("makerspace", "legacy_role"), name="makerspacerole_legacy_uniq"),
                    models.CheckConstraint(condition=models.Q(("is_default", False), ("legacy_role__isnull", False), _connector="OR"), name="makerspacerole_default_has_legacy"),
                ],
            },
        ),
        migrations.AddField(
            model_name="makerspacemembership",
            name="assigned_role",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="memberships", to="makerspaces.makerspacerole"),
        ),
        migrations.AlterField(
            model_name="makerspacemembership",
            name="role",
            field=models.CharField(choices=[("space_manager", "Space Manager"), ("guest_admin", "Guest Admin"), ("inventory_manager", "Inventory Manager"), ("print_manager", "Print Manager"), ("machine_manager", "Machine Manager"), ("custom", "Custom")], default="space_manager", max_length=32),
        ),
    ]
