# Generated by Django 5.1.15 on 2026-07-18 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _free_value(model, makerspace_id, field, base):
    candidate, n = base, 2
    while model.objects.filter(makerspace_id=makerspace_id, **{f"{field}__iexact": candidate}).exists():
        candidate = f"{base}-{n}" if field == "slug" else f"{base} {n}"
        n += 1
    return candidate


def seed_member_role(apps, schema_editor):
    Makerspace = apps.get_model("makerspaces", "Makerspace")
    MakerspaceRole = apps.get_model("makerspaces", "MakerspaceRole")
    for makerspace in Makerspace.objects.all().iterator():
        existing = MakerspaceRole.objects.filter(makerspace_id=makerspace.id, slug="member").first()
        if existing and existing.is_default and existing.is_protected and existing.legacy_role is None:
            continue  # protected Member default already present — idempotent no-op
        # A pre-existing NON-protected custom role must not be silently reused as the
        # actionless Member default. Free the "member" slug/name (CI-unique per space)
        # so the real protected default can be created.
        for role in MakerspaceRole.objects.filter(makerspace_id=makerspace.id):
            if role.is_default and role.is_protected:
                continue
            updates = []
            if (role.slug or "").lower() == "member":
                role.slug = _free_value(MakerspaceRole, makerspace.id, "slug", "member-custom")
                updates.append("slug")
            if (role.name or "").strip().lower() == "member":
                role.name = _free_value(MakerspaceRole, makerspace.id, "name", "Member (custom)")
                updates.append("name")
            if updates:
                role.save(update_fields=updates)
        MakerspaceRole.objects.get_or_create(
            makerspace_id=makerspace.id,
            slug="member",
            defaults={
                "name": "Member", "granted_actions": [], "legacy_role": None,
                "is_default": True, "is_protected": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0040_machine_service_module'),
        ('accounts', '0006_member_registration_and_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakerspaceWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('version', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_email', models.CharField(blank=True, max_length=254)),
                ('kind', models.CharField(choices=[('request', 'Request'), ('invite', 'Invite')], max_length=16)),
                ('state', models.CharField(choices=[('requested', 'Requested'), ('invited', 'Invited'), ('active', 'Active'), ('revoked', 'Revoked')], max_length=16)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='makerspacerole',
            name='makerspacerole_default_has_legacy',
        ),
        migrations.AddField(
            model_name='makerspacemembership',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='makerspacemembership',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_makerspace_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='makerspacemembership',
            name='revocation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='makerspacemembership',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='makerspacemembership',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_makerspace_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='makerspacemembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='makerspacemembership',
            name='waiver_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='makerspacemembership',
            name='waiver_version_accepted',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='makerspacerole',
            constraint=models.CheckConstraint(condition=models.Q(('is_default', False), ('legacy_role__isnull', False), ('is_protected', True), _connector='OR'), name='makerspacerole_default_has_legacy'),
        ),
        migrations.AddField(
            model_name='makerspacewaiver',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_makerspace_waivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='makerspacewaiver',
            name='makerspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='makerspaces.makerspace'),
        ),
        migrations.AddField(
            model_name='makerspacemembership',
            name='accepted_waiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_by_memberships', to='makerspaces.makerspacewaiver'),
        ),
        migrations.AddConstraint(
            model_name='makerspacemembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accepted_waiver__isnull', True), ('waiver_accepted_at__isnull', True), ('waiver_version_accepted__isnull', True)), models.Q(('accepted_waiver__isnull', False), ('waiver_accepted_at__isnull', False), ('waiver_version_accepted__isnull', False)), _connector='OR'), name='membership_waiver_acceptance_all_or_none'),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='assigned_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership_requests', to='makerspaces.makerspacerole'),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_membership_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='makerspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='makerspaces.makerspace'),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='makerspacewaiver',
            constraint=models.UniqueConstraint(fields=('makerspace', 'version'), name='uniq_waiver_version_per_makerspace'),
        ),
        migrations.AddConstraint(
            model_name='makerspacewaiver',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('makerspace',), name='uniq_active_waiver_per_makerspace'),
        ),
        migrations.AddConstraint(
            model_name='membershiprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['requested', 'invited']), ('user__isnull', False)), fields=('makerspace', 'user'), name='uniq_open_membership_request_user'),
        ),
        migrations.AddConstraint(
            model_name='membershiprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['requested', 'invited']), models.Q(('invite_email', ''), _negated=True)), fields=('makerspace', 'invite_email'), name='uniq_open_membership_request_email'),
        ),
        migrations.RunPython(seed_member_role, migrations.RunPython.noop),
    ]
