# Generated by Django 5.1.15 on 2026-07-18 11:10

import apps.makerspaces.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0041_member_memberships_waivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspace',
            name='presence_preset_minutes',
            field=models.JSONField(blank=True, default=list, validators=[apps.makerspaces.validators.validate_presence_presets]),
        ),
    ]
