# Generated by Django 5.1.15 on 2026-07-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0042_makerspace_presence_preset_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makerspace',
            name='public_print_status_lookup_policy',
            field=models.CharField(choices=[('token_only', 'Token only'), ('email_unverified', 'Email unverified'), ('checkin_verified', 'Check-In verified')], default='token_only', max_length=32),
        ),
    ]
