# Generated by Django 6.0 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makerspaces", "0043_alter_makerspace_public_print_status_lookup_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makerspace",
            name="public_print_status_lookup_policy",
            field=models.CharField(
                choices=[
                    ("token_only", "Token only"),
                    ("email_unverified", "Email unverified"),
                ],
                default="token_only",
                max_length=32,
            ),
        ),
    ]
