# Generated by Django 6.0 on 2026-07-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makerspaces", "0044_alter_makerspace_public_print_status_lookup_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="makerspace",
            name="membership_policy",
            field=models.CharField(
                choices=[
                    ("request", "Request"),
                    ("open", "Open"),
                    ("invite_only", "Invite only"),
                ],
                default="request",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="makerspace",
            name="referrals_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="makerspacemembership",
            name="can_refer",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="makerspacemembership",
            name="can_verify",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="makerspacemembership",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="makerspacemembership",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="membershiprequest",
            name="auto_activate_on_claim",
            field=models.BooleanField(default=False),
        ),
    ]
