# Generated by Django 5.1.15 on 2026-07-21 07:23

import apps.makerspaces.capabilities
from django.db import migrations, models


def migrate_legacy_self_checkout(apps, schema_editor):
    Makerspace = apps.get_model("makerspaces", "Makerspace")
    for makerspace in Makerspace.objects.order_by("id").iterator():
        makerspace.enabled_features = (
            ["inventory.self_checkout"]
            if "self_checkout" in (makerspace.enabled_modules or [])
            else []
        )
        makerspace.save(update_fields=["enabled_features"])


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0046_retire_print_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspace',
            name='enabled_features',
            field=models.JSONField(blank=True, default=apps.makerspaces.capabilities.default_enabled_features),
        ),
        migrations.RunPython(migrate_legacy_self_checkout, migrations.RunPython.noop),
    ]
