# Generated by Django 5.1.15 on 2026-07-21

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("makerspaces", "0047_capabilities")]

    operations = [
        migrations.AddField(model_name="makerspace", name="geofence_enabled", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="makerspace", name="geofence_latitude", field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[MinValueValidator(-90), MaxValueValidator(90)])),
        migrations.AddField(model_name="makerspace", name="geofence_longitude", field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[MinValueValidator(-180), MaxValueValidator(180)])),
        migrations.AddField(model_name="makerspace", name="geofence_radius_m", field=models.PositiveIntegerField(default=25, validators=[MinValueValidator(1)])),
    ]
