# Generated by Django 5.1.15 on 2026-07-23 02:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_member_registration_and_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAttestationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('apple', 'Apple'), ('android', 'Android')], max_length=16)),
                ('app_id', models.CharField(max_length=255)),
                ('signing_identity', models.CharField(max_length=255)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('production', 'Production')], max_length=16)),
                ('challenge_digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at', 'consumed_at'], name='device_challenge_use_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('platform', models.CharField(choices=[('apple', 'Apple'), ('android', 'Android')], max_length=16)),
                ('app_id', models.CharField(max_length=255)),
                ('signing_identity', models.CharField(max_length=255)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('production', 'Production')], max_length=16)),
                ('attestation_subject_fingerprint', models.CharField(max_length=64)),
                ('attested_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_grants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceRefreshFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('reuse_detected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_families', to='accounts.devicegrant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_refresh_families', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('token_fingerprint', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('blacklisted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='accounts.devicerefreshfamily')),
            ],
        ),
        migrations.AddIndex(
            model_name='devicegrant',
            index=models.Index(fields=['user', 'status'], name='device_grant_user_idx'),
        ),
        migrations.AddIndex(
            model_name='devicerefreshfamily',
            index=models.Index(fields=['grant', 'revoked_at'], name='device_family_grant_idx'),
        ),
        migrations.AddIndex(
            model_name='devicerefreshtoken',
            index=models.Index(fields=['family', 'rotated_at'], name='device_refresh_family_idx'),
        ),
    ]
