# Generated by Django 5.1.15 on 2026-07-23 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_deviceattestationchallenge_devicegrant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSocialAuthSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('google_web_client_id', models.CharField(blank=True, default='', max_length=255)),
                ('google_ios_client_id', models.CharField(blank=True, default='', max_length=255)),
                ('google_android_client_id', models.CharField(blank=True, default='', max_length=255)),
                ('apple_service_id', models.CharField(blank=True, default='', max_length=255)),
                ('apple_native_app_ids', models.JSONField(blank=True, default=list)),
                ('apple_team_id', models.CharField(blank=True, default='', max_length=64)),
                ('apple_key_id', models.CharField(blank=True, default='', max_length=64)),
                ('apple_private_key', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('apple', 'Apple')], max_length=16)),
                ('provider_sub', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_sub'), name='uniq_social_provider_sub'), models.UniqueConstraint(fields=('user', 'provider'), name='uniq_social_user_provider')],
            },
        ),
        migrations.CreateModel(
            name='SocialLoginNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('apple', 'Apple')], max_length=16)),
                ('surface', models.CharField(choices=[('member', 'Member'), ('staff', 'Staff')], max_length=16)),
                ('delivery', models.CharField(choices=[('web', 'Web'), ('device', 'Device')], max_length=16)),
                ('client_platform', models.CharField(choices=[('web', 'Web'), ('ios', 'iOS'), ('android', 'Android')], max_length=16)),
                ('nonce_digest', models.CharField(max_length=64, unique=True)),
                ('origin', models.CharField(blank=True, default='', max_length=512)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_login_nonces', to='accounts.devicegrant')),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at', 'consumed_at'], name='social_nonce_use_idx')],
            },
        ),
    ]
