# Generated by Django 5.1.15 on 2026-06-21 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('makerspaces', '0023_makerspace_map_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(choices=[('hardware', 'Hardware'), ('printing', 'Printing')], max_length=16)),
                ('audience', models.CharField(choices=[('requester', 'Requester'), ('staff', 'Staff')], max_length=16)),
                ('key', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=200)),
                ('text_body', models.TextField()),
                ('html_body', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='makerspaces.makerspace')),
            ],
            options={
                'ordering': ['makerspace__name', 'stream', 'audience', 'key'],
                'constraints': [models.UniqueConstraint(fields=('makerspace', 'stream', 'audience', 'key'), name='uniq_email_template_per_space')],
            },
        ),
    ]
