# Generated by Django 5.1.15 on 2026-07-16 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_dailyemailcounter'),
        ('makerspaces', '0037_makerspace_mattermost_webhook_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNotificationCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('slack', 'Slack'), ('mattermost', 'Mattermost')], max_length=16)),
                ('day', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_notification_counters', to='makerspaces.makerspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('makerspace', 'channel', 'day'), name='uniq_daily_notify_counter')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('slack', 'Slack'), ('mattermost', 'Mattermost')], max_length=16)),
                ('feature', models.CharField(choices=[('hardware_requests', 'Hardware requests'), ('printing', 'Printing'), ('events', 'Events'), ('bookings', 'Bookings'), ('maintenance', 'Maintenance')], max_length=32)),
                ('event', models.CharField(max_length=64)),
                ('text_body', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=8)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_delivery_logs', to='makerspaces.makerspace')),
            ],
            options={
                'indexes': [models.Index(fields=['makerspace', 'channel', '-created_at'], name='notifylog_space_chan_idx'), models.Index(fields=['status'], name='notifylog_status_idx'), models.Index(fields=['makerspace', 'status', '-created_at'], name='notifylog_space_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('hardware_requests', 'Hardware requests'), ('printing', 'Printing'), ('events', 'Events'), ('bookings', 'Bookings'), ('maintenance', 'Maintenance')], max_length=32)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('slack', 'Slack'), ('mattermost', 'Mattermost')], max_length=16)),
                ('enabled', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='makerspaces.makerspace')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['makerspace_id', 'feature', 'channel'],
                'constraints': [models.UniqueConstraint(fields=('makerspace', 'feature', 'channel'), name='uniq_notify_pref_cell')],
            },
        ),
    ]
