# Generated by Django 5.1.15 on 2026-07-23 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_deviceattestationchallenge_devicegrant_and_more'),
        ('integrations', '0014_retire_print_manager_notification_targets'),
        ('makerspaces', '0049_membership_dues_and_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPushSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('fcm_service_account', models.TextField(blank=True, default='')),
                ('apns_private_key', models.TextField(blank=True, default='')),
                ('apns_team_id', models.CharField(blank=True, default='', max_length=64)),
                ('apns_key_id', models.CharField(blank=True, default='', max_length=64)),
                ('apns_topic', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dailynotificationcounter',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('slack', 'Slack'), ('mattermost', 'Mattermost'), ('native_push', 'Native push')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationdeliverylog',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('slack', 'Slack'), ('mattermost', 'Mattermost'), ('native_push', 'Native push')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('slack', 'Slack'), ('mattermost', 'Mattermost'), ('native_push', 'Native push')], max_length=16),
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_ciphertext', models.TextField()),
                ('token_fingerprint', models.CharField(max_length=64)),
                ('provider', models.CharField(choices=[('fcm', 'FCM'), ('apns', 'APNs')], max_length=8)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('production', 'Production')], max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to='accounts.devicegrant')),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to='makerspaces.makerspace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['makerspace', 'active', 'provider'], name='push_device_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('makerspace', 'provider', 'environment', 'token_fingerprint'), name='uniq_push_token_fingerprint')],
            },
        ),
    ]
