# Generated by Django 6.0 on 2026-07-21

import django.db.models.deletion
from django.core.validators import RegexValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("makerspaces", "0047_capabilities"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakerspacePaymentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_secret_key", models.TextField(blank=True, default="")),
                ("stripe_webhook_secret", models.TextField(blank=True, default="")),
                ("default_currency", models.CharField(default="usd", max_length=3, validators=[RegexValidator(message="Default currency must be a three-letter lowercase ISO currency code.", regex="^[a-z]{3}$")])), 
                (
                    "makerspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_settings",
                        to="makerspaces.makerspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "makerspace payment settings",
                "verbose_name_plural": "makerspace payment settings",
            },
        ),
    ]
