# Generated by Django 5.1.15 on 2026-07-23 02:35

from django.db import migrations, models


def backfill_checkout_rail(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    Payment.objects.filter(
        models.Q(stripe_checkout_session_id__isnull=False)
        | ~models.Q(stripe_checkout_url='')
    ).update(online_rail='checkout')


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_payment_subject_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='online_rail',
            field=models.CharField(blank=True, choices=[('checkout', 'Stripe Checkout'), ('native_payment_intent', 'Native payment intent')], max_length=32, null=True),
        ),
        migrations.RunPython(backfill_checkout_rail, migrations.RunPython.noop),
    ]
