# Generated by Django 5.1.15 on 2026-07-14 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('makerspaces', '0026_makerspace_domain_verification'),
        ('printing', '0019_filament_adjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='idle', max_length=20)),
                ('firmware_version', models.CharField(blank=True, max_length=100)),
                ('camera_feed_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linked_print_printer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine', to='printing.printprinter')),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='makerspaces.makerspace')),
            ],
            options={
                'ordering': ['makerspace__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MachineDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('manual', 'Manual'), ('sop', 'SOP')], max_length=16)),
                ('object_key', models.CharField(max_length=255, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='machines.machine')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=16)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='machines.machine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_builtin', models.BooleanField(default=False)),
                ('managing_action', models.CharField(blank=True, default='', max_length=64)),
                ('makerspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_types', to='makerspaces.makerspace')),
            ],
            options={
                'ordering': ['makerspace__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='machines.machinetype'),
        ),
        migrations.CreateModel(
            name='MachineUsageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(choices=[('manual', 'Manual')], default='manual', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_entries', to='machines.machine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('operate', 'Operate'), ('manage', 'Manage'), ('full', 'Full')], max_length=16)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='machines.machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('machine', 'user')},
            },
        ),
        migrations.AddConstraint(
            model_name='machinetype',
            constraint=models.UniqueConstraint(condition=models.Q(('makerspace__isnull', True)), fields=('slug',), name='uniq_global_machinetype_slug'),
        ),
        migrations.AddConstraint(
            model_name='machinetype',
            constraint=models.UniqueConstraint(condition=models.Q(('makerspace__isnull', False)), fields=('makerspace', 'slug'), name='uniq_lab_machinetype_slug'),
        ),
        migrations.AddConstraint(
            model_name='machinetype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_builtin', True), ('makerspace__isnull', True)), models.Q(('is_builtin', False), ('makerspace__isnull', False)), _connector='OR'), name='machinetype_builtin_is_global'),
        ),
        migrations.AddConstraint(
            model_name='machineusageentry',
            constraint=models.CheckConstraint(condition=models.Q(('hours__gt', 0)), name='machineusage_hours_positive'),
        ),
    ]
