# Generated by Django 5.1.15 on 2026-07-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_backfill_printer_machines'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='image_key',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
