# Generated by Django 5.1.15 on 2026-07-15 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryproduct_image_key'),
        ('machines', '0004_machine_image_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(choices=[('count', 'Count'), ('grams', 'Grams')], max_length=10)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('remaining', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('low_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='machines.machine')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_consumables', to='inventory.inventoryproduct')),
            ],
            options={
                'ordering': ['measurement', 'label', 'product__name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('measurement', 'count'), ('product__isnull', False)), models.Q(('measurement', 'grams'), ('product__isnull', True)), _connector='OR'), name='machineconsumable_count_xor_grams')],
                'unique_together': {('machine', 'product')},
            },
        ),
    ]
