# Generated by Django 5.1.15 on 2026-07-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_machine_consumables'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
