# Generated by Django 5.1.15 on 2026-07-17 21:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryproduct_image_key'),
        ('machines', '0007_machine_usage_time_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_buckets', to='machines.machine')),
            ],
            options={
                'ordering': ['machine__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MachineServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.TextField(blank=True)),
                ('contact_email', models.TextField(blank=True)),
                ('contact_phone', models.TextField(blank=True)),
                ('public_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('collected', 'Collected'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_minutes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_minutes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fail_percent_complete', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_service_requests', to=settings.AUTH_USER_MODEL)),
                ('assigned_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to='machines.machine')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_service_requests', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_service_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_service_requests', to=settings.AUTH_USER_MODEL)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='machines.servicebucket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(choices=[('count', 'Count'), ('grams', 'Grams')], max_length=10)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('machine_consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_request_consumptions', to='machines.machineconsumable')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventoryproduct')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='machines.machineservicerequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('attachment', 'Attachment')], max_length=16)),
                ('object_key', models.CharField(max_length=255, unique=True)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('owner_user_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attached_at', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_request_files', to='machines.machine')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='machines.machineservicerequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='servicebucket',
            index=models.Index(fields=['machine', 'is_active'], name='service_bucket_machine_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicebucket',
            constraint=models.UniqueConstraint(fields=('machine', 'name'), name='uniq_service_bucket_machine_name'),
        ),
        migrations.AddIndex(
            model_name='machineservicerequest',
            index=models.Index(fields=['requester', '-created_at'], name='servicereq_requester_created_idx'),
        ),
        migrations.AddIndex(
            model_name='machineservicerequest',
            index=models.Index(fields=['bucket', 'status', '-created_at'], name='servicereq_bucket_status_idx'),
        ),
        migrations.AddIndex(
            model_name='machineservicerequest',
            index=models.Index(fields=['assigned_machine', 'status', '-created_at'], name='servicereq_machine_status_idx'),
        ),
        migrations.AddIndex(
            model_name='machineservicerequest',
            index=models.Index(fields=['completed_at'], name='servicereq_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='machineservicerequest',
            index=models.Index(fields=['failed_at'], name='servicereq_failed_idx'),
        ),
        migrations.AddConstraint(
            model_name='machineservicerequest',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_minutes__gte', 0)), name='service_req_est_minutes_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='machineservicerequest',
            constraint=models.CheckConstraint(condition=models.Q(('actual_minutes__gte', 0)), name='service_req_actual_minutes_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='machineservicerequest',
            constraint=models.CheckConstraint(condition=models.Q(('fail_percent_complete__gte', 0), ('fail_percent_complete__lte', 100)), name='service_req_fail_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='servicerequestconsumption',
            constraint=models.UniqueConstraint(fields=('service_request', 'machine_consumable'), name='uniq_service_request_consumable'),
        ),
        migrations.AddConstraint(
            model_name='servicerequestconsumption',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='service_req_consumption_qty_positive'),
        ),
        # N1 deliberately backfills no historical service requests.
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
        migrations.RunSQL(
            sql="""
CREATE OR REPLACE FUNCTION service_request_consumption_reject_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' AND current_setting('app.allow_immutable_delete', true) = 'on' THEN
        RETURN OLD;
    END IF;
    RAISE EXCEPTION 'append-only/immutable table: % not allowed', TG_OP;
END;
$$;

CREATE TRIGGER service_request_consumption_no_update
BEFORE UPDATE ON machines_servicerequestconsumption
FOR EACH ROW EXECUTE FUNCTION service_request_consumption_reject_mutation();

CREATE TRIGGER service_request_consumption_no_delete
BEFORE DELETE ON machines_servicerequestconsumption
FOR EACH ROW EXECUTE FUNCTION service_request_consumption_reject_mutation();
""",
            reverse_sql="""
DROP TRIGGER IF EXISTS service_request_consumption_no_update ON machines_servicerequestconsumption;
DROP TRIGGER IF EXISTS service_request_consumption_no_delete ON machines_servicerequestconsumption;
DROP FUNCTION IF EXISTS service_request_consumption_reject_mutation();
""",
        ),
    ]
