# Generated by Django 5.1.15 on 2026-07-18

from django.db import migrations, models
import apps.machines.service_file_policies


class Migration(migrations.Migration):

    dependencies = [("machines", "0008_machine_service_requests")]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="service_file_policy",
            field=models.JSONField(
                default=apps.machines.service_file_policies.default_service_file_policy,
                validators=[apps.machines.service_file_policies.validate_service_file_policy],
            ),
        ),
        migrations.AddField(
            model_name="servicerequestfile",
            name="file_policy_name",
            field=models.CharField(default="documents", max_length=64),
        ),
        migrations.AddField(
            model_name="servicerequestfile",
            name="file_policy_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
