# Generated by Django 5.1.15 on 2026-07-18 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_service_request_file_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='machineservicerequest',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_machine_service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='machineservicerequest',
            index=models.Index(fields=['member', '-created_at'], name='servicereq_member_created_idx'),
        ),
    ]
