# Generated by Django 5.1.15 on 2026-07-20 05:32

from django.db import migrations, models


PRINTER_CONFIG = {
    "schema": "3d-printer-v1",
    "service_payload_schema": "printer-v1",
    "machine_payload_schema": "printer-machine-v1",
    "accepted_materials": ["PLA", "PETG", "TPU"],
    "accepted_colours": ["Black", "Blue", "Green", "Red", "White", "Gray"],
    "pooled_service_queue": True,
    "payment_enabled": True,
    "typed_consumable_pools": True,
    "service_file_policy": {"name": "printer", "version": 1},
    "printer_hours": True,
    "run_sheet_required": True,
}


def configure_printer_type(apps, schema_editor):
    MachineType = apps.get_model("machines", "MachineType")
    Machine = apps.get_model("machines", "Machine")
    MachineType.objects.filter(
        makerspace__isnull=True, slug="3d_printer"
    ).update(capability_config=PRINTER_CONFIG)
    # Preserve linked printer rows without reading or moving any printing data.
    # Their real model remains on the temporary bridge until B4/B7; this explicit
    # placeholder keeps the new run-sheet payload contract non-empty meanwhile.
    Machine.objects.filter(
        machine_type__makerspace__isnull=True,
        machine_type__slug="3d_printer",
        type_payload={},
    ).update(type_payload={"model": "Legacy printer"})


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0011_pooled_service_consumable_kernel'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='type_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(configure_printer_type, migrations.RunPython.noop),
    ]
